"""Add email field to reservations

Revision ID: 96abb4370291
Revises: ca1c84adfb9a
Create Date: 2025-07-21 18:15:56.194595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96abb4370291'
down_revision = 'ca1c84adfb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
